import os
from datetime import datetime
from fpdf import FPDF
from PIL import Image


class MedicalReportPDF(FPDF):
    def __init__(self, title='MediVision AI - Radiology Diagnostic Report'):
        super().__init__('P', 'mm', 'A4')
        self.set_auto_page_break(auto=True, margin=25)
        self.report_title = title

    def header(self):
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(30, 41, 59)
        self.cell(0, 12, self.report_title, 0, 1, 'C')
        self.set_font('Helvetica', '', 9)
        self.set_text_color(100, 116, 139)
        self.cell(0, 6, f'Generated: {datetime.now().strftime("%B %d, %Y at %I:%M %p")}', 0, 1, 'C')
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}}', 0, 0, 'C')
        self.cell(0, 10, 'MediVision AI - Confidential Medical Document', 0, 0, 'C')

    def add_section_title(self, title):
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(13, 110, 253)
        self.cell(0, 8, title, 0, 1, 'L')
        self.set_draw_color(13, 110, 253)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def add_field(self, label, value):
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(51, 65, 85)
        self.cell(45, 7, label, 0, 0)
        self.set_font('Helvetica', '', 10)
        self.set_text_color(30, 41, 59)
        self.cell(0, 7, str(value), 0, 1)

    def add_image_with_caption(self, image_path, caption, max_width=180, max_height=120):
        if not image_path or not os.path.exists(image_path):
            self.set_font('Helvetica', 'I', 9)
            self.set_text_color(148, 163, 184)
            self.cell(0, 7, f'[{caption} - Not Available]', 0, 1, 'C')
            self.ln(4)
            return

        try:
            img = Image.open(image_path)
            img_width, img_height = img.size
            
            aspect = img_width / img_height
            display_width = min(max_width, max_height * aspect)
            display_height = display_width / aspect
            
            if display_height > max_height:
                display_height = max_height
                display_width = display_height * aspect

            x = (210 - display_width) / 2
            self.image(image_path, x=x, y=self.get_y(), w=display_width, h=display_height)
            self.ln(display_height + 2)
            
            self.set_font('Helvetica', 'I', 9)
            self.set_text_color(100, 116, 139)
            self.cell(0, 5, caption, 0, 1, 'C')
            self.ln(4)
        except Exception as e:
            self.set_font('Helvetica', 'I', 9)
            self.set_text_color(239, 68, 68)
            self.cell(0, 7, f'[{caption} - Error loading image: {str(e)}]', 0, 1, 'C')
            self.ln(4)

    def add_multiline_text(self, text):
        self.set_font('Helvetica', '', 10)
        self.set_text_color(30, 41, 59)
        # Remove emojis and special unicode characters for Helvetica font
        import re
        clean_text = re.sub(r'[^\x00-\xFF]', '', text)
        self.multi_cell(0, 5, clean_text)
        self.ln(2)

    def add_disclaimer(self):
        self.ln(6)
        self.set_draw_color(13, 110, 253)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)
        self.set_font('Helvetica', 'B', 9)
        self.set_text_color(239, 68, 68)
        self.cell(0, 5, 'IMPORTANT MEDICAL DISCLAIMER:', 0, 1)
        self.set_font('Helvetica', '', 8)
        self.set_text_color(100, 116, 139)
        disclaimer = (
            "This report is generated by MediVision AI for diagnostic assistance purposes only. "
            "It does not constitute a definitive medical diagnosis. All findings must be verified "
            "by a qualified radiologist or orthopedic surgeon. AI-generated confidence scores "
            "represent algorithmic probability, not clinical certainty. Treatment decisions should "
            "always be made by licensed medical professionals based on comprehensive clinical evaluation."
        )
        self.multi_cell(0, 4, disclaimer)
        self.ln(3)
        
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 5, 'End of Report - MediVision AI Radiology Workstation', 0, 1, 'C')


def generate_bone_detection_report(
    patient_name,
    patient_age,
    patient_gender,
    fracture_type,
    confidence,
    severity,
    description,
    treatment,
    original_image_path,
    highlighted_image_path,
    thermal_image_path,
    output_path
):
    pdf = MedicalReportPDF('MediVision AI - Bone Fracture Detection Report')
    pdf.alias_nb_pages()
    pdf.add_page()

    pdf.add_section_title('PATIENT INFORMATION')
    pdf.add_field('Patient Name:', patient_name)
    pdf.add_field('Age:', f'{patient_age} years')
    pdf.add_field('Gender:', patient_gender)
    pdf.add_field('Report Date:', datetime.now().strftime('%B %d, %Y'))
    pdf.add_field('Report Time:', datetime.now().strftime('%I:%M %p'))
    pdf.ln(4)

    pdf.add_section_title('DIAGNOSTIC RESULTS - BONE FRACTURE ANALYSIS')
    pdf.add_field('Fracture Type:', fracture_type.capitalize())
    pdf.add_field('Confidence Level:', f'{confidence:.2f}%')
    pdf.add_field('Severity:', severity)
    pdf.ln(2)

    pdf.add_section_title('CLINICAL DESCRIPTION')
    pdf.add_multiline_text(description)
    
    pdf.add_section_title('RECOMMENDED TREATMENT PLAN')
    pdf.add_multiline_text(treatment)
    pdf.ln(4)

    pdf.add_section_title('MEDICAL IMAGING ANALYSIS - X-RAY')
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 7, '1. Original X-Ray Image', 0, 1)
    pdf.add_image_with_caption(original_image_path, 'Original X-Ray Image', max_width=170, max_height=110)
    
    pdf.ln(2)
    pdf.cell(0, 7, '2. Fracture Highlighted Detection View', 0, 1)
    pdf.add_image_with_caption(highlighted_image_path, 'AI-Detected Fracture Region (Red Boundary & Crosshairs)', max_width=170, max_height=110)
    
    pdf.ln(2)
    pdf.cell(0, 7, '3. Thermal Intensity Heatmap View', 0, 1)
    pdf.add_image_with_caption(thermal_image_path, 'Thermal Gradient Heatmap (JET Colormap - Structural Intensity)', max_width=170, max_height=110)

    pdf.add_disclaimer()
    pdf.output(output_path)
    return output_path


def generate_mri_ct_report(
    patient_name,
    patient_age,
    patient_gender,
    scan_type,
    anomaly_type,
    confidence,
    severity,
    description,
    treatment,
    original_image_path,
    highlighted_image_path,
    thermal_image_path,
    output_path
):
    pdf = MedicalReportPDF(f'MediVision AI - {scan_type} Scan Analysis Report')
    pdf.alias_nb_pages()
    pdf.add_page()

    pdf.add_section_title('PATIENT INFORMATION')
    pdf.add_field('Patient Name:', patient_name)
    pdf.add_field('Age:', f'{patient_age} years')
    pdf.add_field('Gender:', patient_gender)
    pdf.add_field('Scan Type:', scan_type)
    pdf.add_field('Report Date:', datetime.now().strftime('%B %d, %Y'))
    pdf.add_field('Report Time:', datetime.now().strftime('%I:%M %p'))
    pdf.ln(4)

    pdf.add_section_title(f'DIAGNOSTIC RESULTS - {scan_type} ANOMALY ANALYSIS')
    pdf.add_field('Anomaly Classification:', anomaly_type.replace('_', ' ').title())
    pdf.add_field('Confidence Level:', f'{confidence:.2f}%')
    pdf.add_field('Severity:', severity)
    pdf.ln(2)

    pdf.add_section_title('CLINICAL DESCRIPTION')
    pdf.add_multiline_text(description)
    
    pdf.add_section_title('RECOMMENDED TREATMENT PLAN')
    pdf.add_multiline_text(treatment)
    pdf.ln(4)

    pdf.add_section_title(f'MEDICAL IMAGING ANALYSIS - {scan_type}')
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 7, '1. Original Scan Image', 0, 1)
    pdf.add_image_with_caption(original_image_path, f'Original {scan_type} Scan Image', max_width=170, max_height=110)
    
    pdf.ln(2)
    pdf.cell(0, 7, '2. Anomaly Highlighted View', 0, 1)
    pdf.add_image_with_caption(highlighted_image_path, f'AI-Detected Anomaly Region ({scan_type})', max_width=170, max_height=110)
    
    pdf.ln(2)
    pdf.cell(0, 7, '3. Thermal Intensity Heatmap View', 0, 1)
    pdf.add_image_with_caption(thermal_image_path, f'Thermal Gradient Heatmap (JET Colormap - Structural Intensity)', max_width=170, max_height=110)

    pdf.add_disclaimer()
    pdf.output(output_path)
    return output_path


def generate_report_analysis_report(
    patient_name,
    patient_age,
    patient_gender,
    summary_text,
    output_path
):
    pdf = MedicalReportPDF('MediVision AI - Medical Report Analysis Summary')
    pdf.alias_nb_pages()
    pdf.add_page()

    pdf.add_section_title('PATIENT INFORMATION')
    pdf.add_field('Patient Name:', patient_name)
    pdf.add_field('Age:', f'{patient_age} years')
    pdf.add_field('Gender:', patient_gender)
    pdf.add_field('Report Date:', datetime.now().strftime('%B %d, %Y'))
    pdf.add_field('Report Time:', datetime.now().strftime('%I:%M %p'))
    pdf.ln(4)

    pdf.add_section_title('AI MEDICAL REPORT ANALYSIS SUMMARY')
    pdf.add_multiline_text(summary_text)

    pdf.add_disclaimer()
    pdf.output(output_path)
    return output_path


def generate_symptom_advisor_report(
    patient_name,
    patient_age,
    patient_gender,
    symptoms,
    advice_text,
    output_path
):
    pdf = MedicalReportPDF('MediVision AI - Symptom & Medicine Advisory Report')
    pdf.alias_nb_pages()
    pdf.add_page()

    pdf.add_section_title('PATIENT INFORMATION')
    pdf.add_field('Patient Name:', patient_name)
    pdf.add_field('Age:', f'{patient_age} years')
    pdf.add_field('Gender:', patient_gender)
    pdf.add_field('Report Date:', datetime.now().strftime('%B %d, %Y'))
    pdf.add_field('Report Time:', datetime.now().strftime('%I:%M %p'))
    pdf.ln(4)

    pdf.add_section_title('REPORTED SYMPTOMS')
    pdf.add_multiline_text(symptoms)
    pdf.ln(2)

    pdf.add_section_title('MEDICINE SUGGESTIONS & CLINICAL ADVISORY')
    pdf.add_multiline_text(advice_text)

    pdf.add_disclaimer()
    pdf.output(output_path)
    return output_path


def generate_master_report(
    patient_name,
    patient_age,
    patient_gender,
    bone_data=None,
    mri_ct_data=None,
    report_analysis_data=None,
    symptom_advisor_data=None,
    output_path=None
):
    """
    Generate a comprehensive master report combining all sections.
    
    Args:
        bone_data: dict with keys: fracture_type, confidence, severity, description, treatment,
                   original_image_path, highlighted_image_path, thermal_image_path
        mri_ct_data: dict with keys: scan_type, anomaly_type, confidence, severity, description, treatment,
                     original_image_path, highlighted_image_path, thermal_image_path
        report_analysis_data: dict with key: summary_text
        symptom_advisor_data: dict with keys: symptoms, advice_text
    """
    pdf = MedicalReportPDF('MediVision AI - Comprehensive Multi-Modality Diagnostic Report')
    pdf.alias_nb_pages()
    pdf.add_page()

    # Patient Information
    pdf.add_section_title('PATIENT INFORMATION')
    pdf.add_field('Patient Name:', patient_name)
    pdf.add_field('Age:', f'{patient_age} years')
    pdf.add_field('Gender:', patient_gender)
    pdf.add_field('Report Date:', datetime.now().strftime('%B %d, %Y'))
    pdf.add_field('Report Time:', datetime.now().strftime('%I:%M %p'))
    pdf.ln(4)

    # Table of Contents
    pdf.add_section_title('TABLE OF CONTENTS')
    toc_items = []
    if bone_data:
        toc_items.append('1. Bone Fracture Detection (X-Ray Analysis)')
    if mri_ct_data:
        toc_items.append(f"2. {mri_ct_data.get('scan_type', 'MRI/CT')} Scan Anomaly Analysis")
    if report_analysis_data:
        toc_items.append('3. Medical Report AI Analysis Summary')
    if symptom_advisor_data:
        toc_items.append('4. Symptom & Medicine Advisory')
    
    for item in toc_items:
        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(0, 7, item, 0, 1)
    pdf.ln(4)

    # Section 1: Bone Detection
    if bone_data:
        pdf.add_section_title('1. BONE FRACTURE DETECTION - X-RAY ANALYSIS')
        pdf.add_field('Fracture Type:', bone_data.get('fracture_type', 'N/A').capitalize())
        pdf.add_field('Confidence Level:', f"{bone_data.get('confidence', 0):.2f}%")
        pdf.add_field('Severity:', bone_data.get('severity', 'N/A'))
        pdf.ln(2)
        
        pdf.add_section_title('CLINICAL DESCRIPTION')
        pdf.add_multiline_text(bone_data.get('description', 'N/A'))
        
        pdf.add_section_title('RECOMMENDED TREATMENT PLAN')
        pdf.add_multiline_text(bone_data.get('treatment', 'N/A'))
        pdf.ln(4)

        pdf.add_section_title('MEDICAL IMAGING - X-RAY')
        pdf.set_font('Helvetica', 'B', 10)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(0, 7, '1.1 Original X-Ray Image', 0, 1)
        pdf.add_image_with_caption(bone_data.get('original_image_path'), 'Original X-Ray Image', max_width=160, max_height=100)
        
        pdf.ln(2)
        pdf.cell(0, 7, '1.2 Fracture Highlighted Detection View', 0, 1)
        pdf.add_image_with_caption(bone_data.get('highlighted_image_path'), 'AI-Detected Fracture Region (Red Boundary & Crosshairs)', max_width=160, max_height=100)
        
        pdf.ln(2)
        pdf.cell(0, 7, '1.3 Thermal Intensity Heatmap View', 0, 1)
        pdf.add_image_with_caption(bone_data.get('thermal_image_path'), 'Thermal Gradient Heatmap (JET Colormap)', max_width=160, max_height=100)
        pdf.ln(6)

    # Section 2: MRI/CT
    if mri_ct_data:
        pdf.add_section_title(f"2. {mri_ct_data.get('scan_type', 'MRI/CT').upper()} SCAN ANOMALY ANALYSIS")
        pdf.add_field('Anomaly Classification:', mri_ct_data.get('anomaly_type', 'N/A').replace('_', ' ').title())
        pdf.add_field('Confidence Level:', f"{mri_ct_data.get('confidence', 0):.2f}%")
        pdf.add_field('Severity:', mri_ct_data.get('severity', 'N/A'))
        pdf.ln(2)
        
        pdf.add_section_title('CLINICAL DESCRIPTION')
        pdf.add_multiline_text(mri_ct_data.get('description', 'N/A'))
        
        pdf.add_section_title('RECOMMENDED TREATMENT PLAN')
        pdf.add_multiline_text(mri_ct_data.get('treatment', 'N/A'))
        pdf.ln(4)

        pdf.add_section_title(f'MEDICAL IMAGING - {mri_ct_data.get("scan_type", "MRI/CT").upper()}')
        pdf.set_font('Helvetica', 'B', 10)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(0, 7, f'2.1 Original {mri_ct_data.get("scan_type", "MRI/CT")} Scan Image', 0, 1)
        pdf.add_image_with_caption(mri_ct_data.get('original_image_path'), f'Original {mri_ct_data.get("scan_type", "MRI/CT")} Scan', max_width=160, max_height=100)
        
        pdf.ln(2)
        pdf.cell(0, 7, f'2.2 Anomaly Highlighted View', 0, 1)
        pdf.add_image_with_caption(mri_ct_data.get('highlighted_image_path'), f'AI-Detected Anomaly Region', max_width=160, max_height=100)
        
        pdf.ln(2)
        pdf.cell(0, 7, f'2.3 Thermal Intensity Heatmap View', 0, 1)
        pdf.add_image_with_caption(mri_ct_data.get('thermal_image_path'), f'Thermal Gradient Heatmap (JET Colormap)', max_width=160, max_height=100)
        pdf.ln(6)

    # Section 3: Report Analysis
    if report_analysis_data:
        pdf.add_section_title('3. MEDICAL REPORT AI ANALYSIS SUMMARY')
        pdf.add_multiline_text(report_analysis_data.get('summary_text', 'N/A'))
        pdf.ln(6)

    # Section 4: Symptom Advisor
    if symptom_advisor_data:
        pdf.add_section_title('4. SYMPTOM & MEDICINE ADVISORY')
        pdf.add_section_title('REPORTED SYMPTOMS')
        pdf.add_multiline_text(symptom_advisor_data.get('symptoms', 'N/A'))
        pdf.ln(2)
        
        pdf.add_section_title('MEDICINE SUGGESTIONS & CLINICAL ADVISORY')
        pdf.add_multiline_text(symptom_advisor_data.get('advice_text', 'N/A'))
        pdf.ln(6)

    pdf.add_disclaimer()
    pdf.output(output_path)
    return output_path


# Backward compatibility aliases
generate_patient_report = generate_bone_detection_report